#!/usr/bin/env python3
"""Generate index.md from the ADR files in this directory.

Hard-errors (nonzero exit, no index.md written) if any ADR-*.md file doesn't
match the format documented in README.md: a title line whose number matches
the filename, and Status/Area fields drawn from fixed, exact-match value
sets. Anything more nuanced than the bare category belongs in the optional
Leaning field or in the body — never appended to Status/Area themselves.

Usage: python3 make_index.py
"""

from __future__ import annotations

import re
import sys
from dataclasses import dataclass
from pathlib import Path

STATUSES = ["Open", "Settled", "Deferred", "Superseded"]
AREAS = ["Language Design", "Implementation", "Future Work"]

FILENAME_RE = re.compile(r"^ADR-(\d{4})-[a-z0-9-]+\.md$")
TITLE_RE = re.compile(r"^# ADR-(\d{4}): (.+)$")
FIELD_RE = re.compile(r"^\*\*([A-Za-z]+):\*\* (.+)$")


@dataclass
class Adr:
    number: int
    filename: str
    title: str
    status: str
    area: str
    leaning: str | None


def parse_adr(path: Path, errors: list[str]) -> Adr | None:
    filename = path.name
    filename_match = FILENAME_RE.match(filename)
    if not filename_match:
        errors.append(f"{filename}: filename doesn't match ADR-NNNN-slug.md")
        return None
    filename_number = int(filename_match.group(1))

    lines = path.read_text().splitlines()
    if not lines:
        errors.append(f"{filename}: file is empty")
        return None

    title_match = TITLE_RE.match(lines[0])
    if not title_match:
        errors.append(f"{filename}: first line isn't '# ADR-NNNN: Title' (got {lines[0]!r})")
        return None
    title_number = int(title_match.group(1))
    title = title_match.group(2).strip()
    if title_number != filename_number:
        errors.append(
            f"{filename}: title says ADR-{title_number:04d} but filename says "
            f"ADR-{filename_number:04d}"
        )
        return None

    # Header block: consecutive "**Field:** value" lines, starting right after
    # the title and its blank line, ending at the next blank line.
    fields: dict[str, str] = {}
    i = 1
    if i < len(lines) and lines[i].strip() == "":
        i += 1
    while i < len(lines) and lines[i].strip() != "":
        field_match = FIELD_RE.match(lines[i])
        if not field_match:
            errors.append(f"{filename}: unexpected line in header block: {lines[i]!r}")
            return None
        fields[field_match.group(1)] = field_match.group(2).strip()
        i += 1

    status = fields.get("Status")
    if status is None:
        errors.append(f"{filename}: missing **Status:** field")
        return None
    if status not in STATUSES:
        errors.append(
            f"{filename}: Status {status!r} is not exactly one of {STATUSES} "
            "(no parentheticals or commentary — put that in Leaning instead)"
        )
        return None

    area = fields.get("Area")
    if area is None:
        errors.append(f"{filename}: missing **Area:** field")
        return None
    if area not in AREAS:
        errors.append(f"{filename}: Area {area!r} is not exactly one of {AREAS}")
        return None

    leaning = fields.get("Leaning")

    return Adr(
        number=filename_number,
        filename=filename,
        title=title,
        status=status,
        area=area,
        leaning=leaning,
    )


def format_entry(adr: Adr) -> str:
    suffix = f" — *{adr.leaning}*" if adr.leaning else ""
    return f"- [ADR-{adr.number:04d}: {adr.title}]({adr.filename}) — **{adr.status}**{suffix}"


def build_index(adrs: list[Adr]) -> str:
    lines = ["# ADR Index", "", "Generated by `make_index.py` — do not edit by hand.", ""]

    lines.append("## Chronological")
    lines.append("")
    for adr in sorted(adrs, key=lambda a: a.number):
        lines.append(format_entry(adr))
    lines.append("")

    lines.append("## By status")
    lines.append("")
    for status in STATUSES:
        group = [a for a in adrs if a.status == status]
        if not group:
            continue
        lines.append(f"### {status}")
        lines.append("")
        for adr in sorted(group, key=lambda a: a.number):
            lines.append(format_entry(adr))
        lines.append("")

    lines.append("## By area")
    lines.append("")
    for area in AREAS:
        group = [a for a in adrs if a.area == area]
        if not group:
            continue
        lines.append(f"### {area}")
        lines.append("")
        for adr in sorted(group, key=lambda a: a.number):
            lines.append(format_entry(adr))
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def fail(errors: list[str]) -> None:
    sys.stderr.write(f"make_index.py: {len(errors)} ADR(s) failed to parse:\n\n")
    for error in errors:
        sys.stderr.write(f"  - {error}\n")
    sys.stderr.write("\nindex.md NOT written.\n")
    sys.exit(1)


def main() -> None:
    directory = Path(__file__).resolve().parent
    paths = sorted(directory.glob("ADR-*.md"))
    if not paths:
        sys.stderr.write(f"make_index.py: no ADR-*.md files found in {directory}\n")
        sys.exit(1)

    errors: list[str] = []
    adrs: list[Adr] = []
    seen_numbers: dict[int, str] = {}
    for path in paths:
        adr = parse_adr(path, errors)
        if adr is None:
            continue
        if adr.number in seen_numbers:
            errors.append(
                f"{path.name}: duplicate ADR number {adr.number:04d} "
                f"(already used by {seen_numbers[adr.number]})"
            )
            continue
        seen_numbers[adr.number] = path.name
        adrs.append(adr)

    if errors:
        fail(errors)

    index_path = directory / "index.md"
    index_path.write_text(build_index(adrs))
    print(f"wrote {index_path} ({len(adrs)} ADRs)")


if __name__ == "__main__":
    main()
