/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 28
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 23
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_var = 1,
  anon_sym_COLON = 2,
  anon_sym_EQ = 3,
  anon_sym_SEMI = 4,
  anon_sym_undefined = 5,
  anon_sym_zeroed = 6,
  anon_sym_struct = 7,
  anon_sym_LBRACE = 8,
  anon_sym_RBRACE = 9,
  anon_sym_fn = 10,
  sym_type = 11,
  sym_expression = 12,
  sym_identifier = 13,
  sym_todo = 14,
  sym_source_file = 15,
  sym_top_level_item = 16,
  sym_var_def = 17,
  sym_var_initializer = 18,
  sym_struct_def = 19,
  sym_fn_def = 20,
  aux_sym_source_file_repeat1 = 21,
  aux_sym_struct_def_repeat1 = 22,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_var] = "var",
  [anon_sym_COLON] = ":",
  [anon_sym_EQ] = "=",
  [anon_sym_SEMI] = ";",
  [anon_sym_undefined] = "undefined",
  [anon_sym_zeroed] = "zeroed",
  [anon_sym_struct] = "struct",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_fn] = "fn",
  [sym_type] = "type",
  [sym_expression] = "expression",
  [sym_identifier] = "identifier",
  [sym_todo] = "todo",
  [sym_source_file] = "source_file",
  [sym_top_level_item] = "top_level_item",
  [sym_var_def] = "var_def",
  [sym_var_initializer] = "var_initializer",
  [sym_struct_def] = "struct_def",
  [sym_fn_def] = "fn_def",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_struct_def_repeat1] = "struct_def_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_var] = anon_sym_var,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_undefined] = anon_sym_undefined,
  [anon_sym_zeroed] = anon_sym_zeroed,
  [anon_sym_struct] = anon_sym_struct,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_fn] = anon_sym_fn,
  [sym_type] = sym_type,
  [sym_expression] = sym_expression,
  [sym_identifier] = sym_identifier,
  [sym_todo] = sym_todo,
  [sym_source_file] = sym_source_file,
  [sym_top_level_item] = sym_top_level_item,
  [sym_var_def] = sym_var_def,
  [sym_var_initializer] = sym_var_initializer,
  [sym_struct_def] = sym_struct_def,
  [sym_fn_def] = sym_fn_def,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_struct_def_repeat1] = aux_sym_struct_def_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_var] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_undefined] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_zeroed] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_struct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_todo] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_top_level_item] = {
    .visible = true,
    .named = true,
  },
  [sym_var_def] = {
    .visible = true,
    .named = true,
  },
  [sym_var_initializer] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_def] = {
    .visible = true,
    .named = true,
  },
  [sym_fn_def] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_def_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(46);
      ADVANCE_MAP(
        ':', 48,
        ';', 50,
        '=', 49,
        'T', 9,
        'f', 33,
        's', 42,
        't', 36,
        'u', 34,
        'v', 21,
        'z', 28,
        '{', 54,
        '}', 55,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(4);
      END_STATE();
    case 2:
      if (lookahead == ':') ADVANCE(1);
      END_STATE();
    case 3:
      if (lookahead == 'D') ADVANCE(10);
      END_STATE();
    case 4:
      if (lookahead == 'E') ADVANCE(19);
      if (lookahead == 'T') ADVANCE(20);
      END_STATE();
    case 5:
      if (lookahead == 'E') ADVANCE(15);
      END_STATE();
    case 6:
      if (lookahead == 'E') ADVANCE(18);
      END_STATE();
    case 7:
      if (lookahead == 'I') ADVANCE(11);
      END_STATE();
    case 8:
      if (lookahead == 'N') ADVANCE(17);
      END_STATE();
    case 9:
      if (lookahead == 'O') ADVANCE(3);
      END_STATE();
    case 10:
      if (lookahead == 'O') ADVANCE(2);
      END_STATE();
    case 11:
      if (lookahead == 'O') ADVANCE(8);
      END_STATE();
    case 12:
      if (lookahead == 'P') ADVANCE(14);
      END_STATE();
    case 13:
      if (lookahead == 'P') ADVANCE(5);
      END_STATE();
    case 14:
      if (lookahead == 'R') ADVANCE(6);
      END_STATE();
    case 15:
      if (lookahead == 'S') ADVANCE(57);
      END_STATE();
    case 16:
      if (lookahead == 'S') ADVANCE(7);
      END_STATE();
    case 17:
      if (lookahead == 'S') ADVANCE(58);
      END_STATE();
    case 18:
      if (lookahead == 'S') ADVANCE(16);
      END_STATE();
    case 19:
      if (lookahead == 'X') ADVANCE(12);
      END_STATE();
    case 20:
      if (lookahead == 'Y') ADVANCE(13);
      END_STATE();
    case 21:
      if (lookahead == 'a') ADVANCE(40);
      END_STATE();
    case 22:
      if (lookahead == 'c') ADVANCE(43);
      END_STATE();
    case 23:
      if (lookahead == 'd') ADVANCE(52);
      END_STATE();
    case 24:
      if (lookahead == 'd') ADVANCE(51);
      END_STATE();
    case 25:
      if (lookahead == 'd') ADVANCE(37);
      END_STATE();
    case 26:
      if (lookahead == 'd') ADVANCE(27);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(31);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(41);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(23);
      END_STATE();
    case 30:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 31:
      if (lookahead == 'f') ADVANCE(32);
      END_STATE();
    case 32:
      if (lookahead == 'i') ADVANCE(35);
      END_STATE();
    case 33:
      if (lookahead == 'n') ADVANCE(56);
      END_STATE();
    case 34:
      if (lookahead == 'n') ADVANCE(26);
      END_STATE();
    case 35:
      if (lookahead == 'n') ADVANCE(30);
      END_STATE();
    case 36:
      if (lookahead == 'o') ADVANCE(25);
      END_STATE();
    case 37:
      if (lookahead == 'o') ADVANCE(60);
      END_STATE();
    case 38:
      if (lookahead == 'o') ADVANCE(29);
      END_STATE();
    case 39:
      if (lookahead == 'r') ADVANCE(44);
      END_STATE();
    case 40:
      if (lookahead == 'r') ADVANCE(47);
      END_STATE();
    case 41:
      if (lookahead == 'r') ADVANCE(38);
      END_STATE();
    case 42:
      if (lookahead == 't') ADVANCE(39);
      END_STATE();
    case 43:
      if (lookahead == 't') ADVANCE(53);
      END_STATE();
    case 44:
      if (lookahead == 'u') ADVANCE(22);
      END_STATE();
    case 45:
      if (lookahead == '}') ADVANCE(55);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(45);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_var);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_undefined);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_zeroed);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_struct);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_type);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_expression);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_todo);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 45},
  [11] = {.lex_state = 45},
  [12] = {.lex_state = 45},
  [13] = {.lex_state = 45},
  [14] = {.lex_state = 45},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 45},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_var] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_undefined] = ACTIONS(1),
    [anon_sym_zeroed] = ACTIONS(1),
    [anon_sym_struct] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [sym_type] = ACTIONS(1),
    [sym_expression] = ACTIONS(1),
    [sym_todo] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(19),
    [sym_top_level_item] = STATE(2),
    [sym_var_def] = STATE(4),
    [sym_struct_def] = STATE(4),
    [sym_fn_def] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_var] = ACTIONS(5),
    [anon_sym_struct] = ACTIONS(7),
    [anon_sym_fn] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(5), 1,
      anon_sym_var,
    ACTIONS(7), 1,
      anon_sym_struct,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    STATE(3), 2,
      sym_top_level_item,
      aux_sym_source_file_repeat1,
    STATE(4), 3,
      sym_var_def,
      sym_struct_def,
      sym_fn_def,
  [22] = 6,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      anon_sym_var,
    ACTIONS(18), 1,
      anon_sym_struct,
    ACTIONS(21), 1,
      anon_sym_fn,
    STATE(3), 2,
      sym_top_level_item,
      aux_sym_source_file_repeat1,
    STATE(4), 3,
      sym_var_def,
      sym_struct_def,
      sym_fn_def,
  [44] = 1,
    ACTIONS(24), 4,
      ts_builtin_sym_end,
      anon_sym_var,
      anon_sym_struct,
      anon_sym_fn,
  [51] = 1,
    ACTIONS(26), 4,
      ts_builtin_sym_end,
      anon_sym_var,
      anon_sym_struct,
      anon_sym_fn,
  [58] = 1,
    ACTIONS(28), 4,
      ts_builtin_sym_end,
      anon_sym_var,
      anon_sym_struct,
      anon_sym_fn,
  [65] = 1,
    ACTIONS(30), 4,
      ts_builtin_sym_end,
      anon_sym_var,
      anon_sym_struct,
      anon_sym_fn,
  [72] = 2,
    STATE(25), 1,
      sym_var_initializer,
    ACTIONS(32), 3,
      anon_sym_undefined,
      anon_sym_zeroed,
      sym_expression,
  [81] = 1,
    ACTIONS(34), 4,
      ts_builtin_sym_end,
      anon_sym_var,
      anon_sym_struct,
      anon_sym_fn,
  [88] = 3,
    ACTIONS(36), 1,
      anon_sym_RBRACE,
    ACTIONS(38), 1,
      sym_identifier,
    STATE(12), 1,
      aux_sym_struct_def_repeat1,
  [98] = 3,
    ACTIONS(40), 1,
      anon_sym_RBRACE,
    ACTIONS(42), 1,
      sym_identifier,
    STATE(11), 1,
      aux_sym_struct_def_repeat1,
  [108] = 3,
    ACTIONS(38), 1,
      sym_identifier,
    ACTIONS(45), 1,
      anon_sym_RBRACE,
    STATE(11), 1,
      aux_sym_struct_def_repeat1,
  [118] = 1,
    ACTIONS(47), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [123] = 1,
    ACTIONS(49), 1,
      sym_identifier,
  [127] = 1,
    ACTIONS(51), 1,
      sym_todo,
  [131] = 1,
    ACTIONS(53), 1,
      sym_identifier,
  [135] = 1,
    ACTIONS(55), 1,
      anon_sym_LBRACE,
  [139] = 1,
    ACTIONS(57), 1,
      anon_sym_COLON,
  [143] = 1,
    ACTIONS(59), 1,
      ts_builtin_sym_end,
  [147] = 1,
    ACTIONS(61), 1,
      sym_type,
  [151] = 1,
    ACTIONS(63), 1,
      anon_sym_SEMI,
  [155] = 1,
    ACTIONS(65), 1,
      anon_sym_SEMI,
  [159] = 1,
    ACTIONS(67), 1,
      anon_sym_COLON,
  [163] = 1,
    ACTIONS(69), 1,
      anon_sym_SEMI,
  [167] = 1,
    ACTIONS(71), 1,
      anon_sym_SEMI,
  [171] = 1,
    ACTIONS(73), 1,
      sym_type,
  [175] = 1,
    ACTIONS(75), 1,
      anon_sym_EQ,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 22,
  [SMALL_STATE(4)] = 44,
  [SMALL_STATE(5)] = 51,
  [SMALL_STATE(6)] = 58,
  [SMALL_STATE(7)] = 65,
  [SMALL_STATE(8)] = 72,
  [SMALL_STATE(9)] = 81,
  [SMALL_STATE(10)] = 88,
  [SMALL_STATE(11)] = 98,
  [SMALL_STATE(12)] = 108,
  [SMALL_STATE(13)] = 118,
  [SMALL_STATE(14)] = 123,
  [SMALL_STATE(15)] = 127,
  [SMALL_STATE(16)] = 131,
  [SMALL_STATE(17)] = 135,
  [SMALL_STATE(18)] = 139,
  [SMALL_STATE(19)] = 143,
  [SMALL_STATE(20)] = 147,
  [SMALL_STATE(21)] = 151,
  [SMALL_STATE(22)] = 155,
  [SMALL_STATE(23)] = 159,
  [SMALL_STATE(24)] = 163,
  [SMALL_STATE(25)] = 167,
  [SMALL_STATE(26)] = 171,
  [SMALL_STATE(27)] = 175,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [15] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [18] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [24] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_top_level_item, 1, 0, 0),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn_def, 2, 0, 0),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_def, 6, 0, 0),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_def, 5, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_def, 7, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_def_repeat1, 2, 0, 0),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_def_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_def_repeat1, 3, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [59] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_initializer, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_nanoc(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "nanoc",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
